### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by 1Blademaster**
Added requirement for flask-CORS

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
This is a simple project that helps illustrate a blog post. CORS is outside the scope of it.

**Comment by 1Blademaster** [comment]
The code doesn't actually working without CORS, it doesn't pass through chrome or anything

**Comment by 1Blademaster** [comment]
I've tried to follow the tutorial but had many problems with CORS as well, decided to stop the tutorial as it just wouldn't work. The actual API works fine with something like PostMan but the JS doesn't work for PUT or DELETE requests

**Comment by miguelgrinberg** [comment]
Depending on how you write your frontend you may need to add CORS headers. If your client is hosted on the same domain and port as your API Chrome and all other browsers should work just fine.

Also note that by simply adding Flask-CORS without giving it a second thought you are opening the door to potential CSRF attacks. If your application needs to work with multiple origins, then I recommend that you only allow specific origins. Flask-CORS with its default configuration will allow all origins, which is something that you should only do if you understand the consequences.

**Pull request closed without merging**
